### ISSUE TITLE
card_swiper EXCEPTION:  _CastError was thrown while dispatching notifications for SwiperController

### ISSUE THREAD

**Issue by siva-rajendran** [lianyagang/flutter_swiper_null_safety#13]
Case:

I am getting this error when my swiper scaffold is in app background.

**[*] I am using smooth_page_indicator for showing custom dots**

Initially i load the main page (which has the swiper) based on conditions i move to some other page, in the background i am getting these errors/exceptions. Only when swiper is in background of flutter app i get this kind of exception.

Any idea to solve !!!

Error: Null check operator used on a null value

Exception Caught:

======== Exception caught by foundation library ====================================================
The following _CastError was thrown while dispatching notifications for SwiperController:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      ScrollPosition.viewportDimension (package:flutter/src/widgets/scroll_position.dart:175:53)
#1      _PagePosition.getPixelsFromPage (package:flutter/src/widgets/page_view.dart:396:19)
#2      PageController.animateToPage (package:flutter/src/widgets/page_view.dart:202:16)
#3      _TransformerPageViewState.onChangeNotifier (package:card_swiper/src/transformer_page_view/transformer_page_view.dart:576:14)
#4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:308:24)
#5      IndexController.next (package:card_swiper/src/transformer_page_view/index_controller.dart:110:5)
#6      _SwiperTimerMixin._onTimer (package:card_swiper/src/swiper.dart:388:17)
(elided 10 frames from class _RawReceivePortImpl, class _Timer, and dart:async)
The SwiperController sending notification was: Instance of 'SwiperController'
====================================================================================================

**Comment by ling9400** [comment]
+1

**Comment by osReilly** [comment]
+1

**Comment by baseSky** [comment]
+1
