### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by sunfa-airgram** [lianyagang/flutter_swiper_null_safety#4]
flutter: ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
flutter: The following _CastError was thrown while dispatching notifications for SwiperController:
flutter: Null check operator used on a null value
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      ScrollPosition.viewportDimension (package:flutter/src/widgets/scroll_position.dart:172:53)
flutter: #1      _PagePosition.getPixelsFromPage (package:flutter/src/widgets/page_view.dart:382:19)
flutter: #2      PageController.animateToPage (package:flutter/src/widgets/page_view.dart:197:16)
flutter: #3      _TransformerPageViewState.onChangeNotifier (package:flutter_swiper_null_safety/src/transformer_page_view/transformer_page_view.dart:590:12)
flutter: #4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:243:25)
flutter: #5      IndexController.next (package:flutter_swiper_null_safety/src/transformer_page_view/index_controller.dart:30:5)
flutter: #6      _SwiperTimerMixin._onTimer (package:flutter_swiper_null_safety/src/swiper.dart:369:18)
flutter: (elided 10 frames from class _RawReceivePortImpl, class _Timer, and dart:async)
flutter:
flutter: The SwiperController sending notification was:
flutter:   Instance of 'SwiperController'

**Comment by sunfa-airgram** [comment]
flutter doctor
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)

**Comment by sunfa-airgram** [comment]
Swiper(
        // autoplay: true,
        controller: _swiperController,
        onIndexChanged: (index) {
          print("index : $index");
          setState(() {
            _currentIndex = index;
          });
        },
        itemBuilder: (context, index) {
          return _buildBannerItem(_titles[index], _images[index]);
        },
        itemCount: _images.length,
      )

**Comment by sunfa-airgram** [comment]
Widget _buildBanner(BuildContext context) {
    return Expanded(
      child: Swiper(
        autoplay: true,
        controller: _swiperController,
        onIndexChanged: (index) {
          print("index : $index");
          setState(() {
            _currentIndex = index;
          });
        },
        itemBuilder: (context, index) {
          return _buildBannerItem(_titles[index], _images[index]);
        },
        itemCount: _images.length,
      ),
    );
  }

**Comment by sunfa-airgram** [comment]
Widget _buildBanner(BuildContext context) {
    return Expanded(
      child: Swiper(
        autoplay: true,
        controller: _swiperController,
        onIndexChanged: (index) {
          print("index : $index");
          setState(() {
            _currentIndex = index;
          });
        },
        itemBuilder: (context, index) {
          return _buildBannerItem(_titles[index], _images[index]);
        },
        itemCount: _images.length,
      ),
    );
  }
